name: Run bot
on:
  push:
  pull_request:
  schedule:
  - cron: '*/1 * * * *'  # every 5 minutes

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pipenv install
    - name: Run main
      run: python main.py 
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}