name: Run bot
on:
  push:
  # pull_request:
  schedule:
  - cron: '0 */6 * * *'  # every 6 hours

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install
    - name: download en_core_web_sm
      run: pipenv run python -m spacy download en_core_web_sm     
    - name: Run main
      run: pipenv run python ./main.py
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}