name: Run bot
on:
  # push:
  # pull_request:
  schedule:
  - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Run main
      run: python ./main.py 
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}